# Creating NHANES DataFrame

The goal of this notebook is to create the NHANES  (**all_nhanes**), data dictionary (**dd**), and lower limit of detection values per analyte (**llod**) dataframes to be uploaded to the app and used for the Distribution Paper.

Author: Julia Geller
Last Edit: 03/06/2022

In [1]:
##creating llod df --> Lower Limit of Detection
import pandas as pd
llod=pd.DataFrame(columns=["Analyte", "Value", "Units", 'Time_Period'])

##function to add llod data to llod
def add_llod(analyte, val, units, tp):
    return llod.append({"Analyte":analyte,"Value":val,"Units":units, "Time_Period":tp}, ignore_index=True)

In [2]:
##Adding NHANES demographic data
##2017-2018
d18= pd.read_sas('DEMO_J.XPT')
d18=d18.rename(columns={"SEQN":"Participant", "RIDEXPRG":"Pregnant", 
                       "RIDAGEYR":"Age","DMDMARTL":"Marital", "DMDHHSZA" : "Child_A",
                         "DMDHHSZB": "Child_B","INDHHIN2":"H_Inc", "INDFMIN2":"F_Inc", 
                          "DMDEDUC2": "Edu","RIDRETH3": "Rac"})
d18=d18[['Participant', 'Pregnant', "Age", 'Marital', 'Child_A', 'Child_B', 'H_Inc', 'F_Inc', 'Edu', 'Rac']]
d18['Time_Period']='2017-18'
d18=d18.astype({"Child_A": int, "Child_B": int})

##demo data 2015-16
d16=pd.read_sas('DEMO_I.XPT')
d16=d16.rename(columns={"SEQN":"Participant", "RIDEXPRG":"Pregnant", 
                       "RIDAGEYR":"Age","DMDMARTL":"Marital", "DMDHHSZA" : "Child_A",
                         "DMDHHSZB": "Child_B","INDHHIN2":"H_Inc", "INDFMIN2":"F_Inc", 
                          "DMDEDUC2": "Edu","RIDRETH3": "Rac"})
d16=d16[['Participant', 'Pregnant', "Age", 'Marital', 'Child_A', 'Child_B', 'H_Inc', 'F_Inc', 'Edu', 'Rac']]
d16['Time_Period']='2015-16'
d16=d16.astype({"Child_A": int, "Child_B": int})


##demo data 2013-14
d14=pd.read_sas('DEMO_H.XPT')
d14=d14.rename(columns={"SEQN":"Participant", "RIDEXPRG":"Pregnant", 
                       "RIDAGEYR":"Age","DMDMARTL":"Marital", "DMDHHSZA" : "Child_A",
                         "DMDHHSZB": "Child_B","INDHHIN2":"H_Inc", "INDFMIN2":"F_Inc", 
                          "DMDEDUC2": "Edu","RIDRETH3": "Rac"})
d14=d14[['Participant', 'Pregnant', "Age", 'Marital', 'Child_A', 'Child_B', 'H_Inc', 'F_Inc', 'Edu', 'Rac']]
d14['Time_Period']='2013-14'
d14=d14.astype({"Child_A": int, "Child_B": int})

##demo data 2011-12
d12=pd.read_sas('DEMO_G.XPT')
d12=d12.rename(columns={"SEQN":"Participant", "RIDEXPRG":"Pregnant", 
                       "RIDAGEYR":"Age","DMDMARTL":"Marital", "DMDHHSZA" : "Child_A",
                         "DMDHHSZB": "Child_B","INDHHIN2":"H_Inc", "INDFMIN2":"F_Inc", 
                          "DMDEDUC2": "Edu","RIDRETH3": "Rac"})
d12=d12[['Participant', 'Pregnant', "Age", 'Marital', 'Child_A', 'Child_B', 'H_Inc', 'F_Inc', 'Edu', 'Rac']]
d12['Time_Period']='2011-12'
d12=d12.astype({"Child_A": int, "Child_B": int})

all_demo=pd.concat([d18, d16, d14, d12])
all_demo[all_demo['Pregnant']==1.0].count()

Participant    247
Pregnant       247
Age            247
Marital        247
Child_A        247
Child_B        247
H_Inc          237
F_Inc          237
Edu            247
Rac            247
Time_Period    247
dtype: int64

In [3]:
###Arsenic - Total - Urine
## For non 2018 to 2017, which urine arsenic data to take
##UTAS
utas18 = pd.read_sas('UTAS_J.XPT')
utas18=utas18.rename(columns={"SEQN": "Participant","URXUAS": "Analyte Value", "URDUASLC": "Blod"})
utas18=utas18[['Participant', 'Analyte Value', 'Blod']]
utas18['Analyte']='Analyte'
llod=add_llod("UTAS",0.23,"ug/L", '2017-18')
##left innner join lc and demo 
m_utas18=pd.merge(
    utas18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##15-16
##UTAS
utas16 = pd.read_sas('UTAS_I.XPT')
utas16=utas16.rename(columns={"SEQN": "Participant","URXUAS": "Analyte Value", "URDUASLC": "Blod"})
utas16=utas16[['Participant', 'Analyte Value']]
utas16['Analyte']='Analyte'
utas16['Blod']=9999
llod=add_llod("UTAS",0.26,"ug/L", '2015-16')
##left innner join lc and demo 
m_utas16=pd.merge(
    utas16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##13-14
##UTAS
utas14 = pd.read_sas('UTAS_H.XPT')
utas14=utas14.rename(columns={"SEQN": "Participant","URXUAS": "Analyte Value", "URDUASLC": "Blod"})
utas14=utas14[['Participant', 'Analyte Value']]
utas14['Analyte']='Analyte'
utas14['Blod']=9999

llod=add_llod("UTAS",0.26,"ug/L", '2013-14')
##left innner join lc and demo 
m_utas14=pd.merge(
    utas14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##11-12
##UTAS
utas12 = pd.read_sas('UAS_G.XPT')
utas12=utas12.rename(columns={"SEQN": "Participant","URXUAS": "Analyte Value", "URDUASLC": "Blod"})
utas12=utas12[['Participant', 'Analyte Value', 'Blod']]
utas12['Analyte']='Analyte'
llod=add_llod("UTAS",1.25,"ug/L", '2011-12')
##left innner join lc and demo 
m_utas12=pd.merge(
    utas12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

all_utas=pd.concat([m_utas18, m_utas16, m_utas14, m_utas12])

In [4]:
import pandas as pd
##Albumin & Creatinine - Urine 
##17-18
lc18 = pd.read_sas('ALB_CR_J.XPT')
lc18=lc18.rename(columns={"SEQN": "Participant", 
                            "URXUMS": "Alb_mg", "URDUMALC": "Alb_Blod", 
                            "URXUCR" : "Cr_mg",
                            "URXCRS":"Cr_umol", "URDUCRLC": "Cr_Blod", 
                            "URDACT":"Alb_to_Cr", 'URXUMA':'Alb_ug'})
lc18=lc18[["Participant","Alb_mg","Alb_Blod","Cr_mg",
                            "Cr_umol", "Cr_Blod", 
                            "Alb_to_Cr", "Alb_ug"]]

##ASK TEAM< alb in mg or ug and cr in mg or umol
l18m=lc18[["Participant","Alb_Blod","Alb_mg"]]
l18m=l18m.rename(columns={"Alb_Blod":'Blod', "Alb_mg":'Analyte Value'})
l18m['Analyte']='UALB_mg'
##left innner join lc and demo 
m_l18m=pd.merge(
    l18m,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

#ASK TEAM< alb in mg or ug and cr in mg or umol
l18u=lc18[["Participant","Alb_Blod","Alb_ug"]]
l18u=l18u.rename(columns={"Alb_Blod":'Blod', "Alb_ug":'Analyte Value'})
l18u['Analyte']='UALB_ug'
##left innner join lc and demo 
m_l18u=pd.merge(
    l18u,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c18m=lc18[["Participant","Cr_Blod","Cr_mg"]]
c18m=c18m.rename(columns={"Cr_Blod":'Blod', "Cr_mg":'Analyte Value'})
c18m['Analyte']='UCRT_mg'
##left innner join lc and demo 
m_c18m=pd.merge(
    c18m,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c18u=lc18[["Participant","Cr_Blod","Cr_umol"]]
c18u=c18u.rename(columns={"Cr_Blod":'Blod', "Cr_umol":'Analyte Value'})
c18u['Analyte']='UCRT_umol'
##left innner join lc and demo 
m_c18u=pd.merge(
    c18u,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

llod=add_llod("UALB",0.30,"ug/mL", '2017-18')
llod=add_llod("UCRT",5.00,"mg/dL", '2017-18')



##15-16
lc16 = pd.read_sas('ALB_CR_I.XPT')
lc16=lc16.rename(columns={"SEQN": "Participant", 
                            "URXUMS": "Alb_mg", "URDUMALC": "Alb_Blod", 
                            "URXUCR" : "Cr_mg",
                            "URXCRS":"Cr_umol", "URDUCRLC": "Cr_Blod", 
                            "URDACT":"Alb_to_Cr", 'URXUMA':'Alb_ug'})
lc16=lc16[["Participant","Alb_mg","Alb_Blod","Cr_mg",
                            "Cr_umol", "Cr_Blod", 
                            "Alb_to_Cr", "Alb_ug"]]

##ASK TEAM< alb in mg or ug and cr in mg or umol
l16m=lc16[["Participant","Alb_Blod","Alb_mg"]]
l16m=l16m.rename(columns={"Alb_Blod":'Blod', "Alb_mg":'Analyte Value'})
l16m['Analyte']='UALB_mg'
##left innner join lc and demo 
m_l16m=pd.merge(
    l16m,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

#ASK TEAM< alb in mg or ug and cr in mg or umol
l16u=lc16[["Participant","Alb_Blod","Alb_ug"]]
l16u=l16u.rename(columns={"Alb_Blod":'Blod', "Alb_ug":'Analyte Value'})
l16u['Analyte']='UALB_ug'
##left innner join lc and demo 
m_l16u=pd.merge(
    l16u,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c16m=lc16[["Participant","Cr_Blod","Cr_mg"]]
c16m=c16m.rename(columns={"Cr_Blod":'Blod', "Cr_mg":'Analyte Value'})
c16m['Analyte']='UCRT_mg'
##left innner join lc and demo 
m_c16m=pd.merge(
    c16m,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c16u=lc16[["Participant","Cr_Blod","Cr_umol"]]
c16u=c16u.rename(columns={"Cr_Blod":'Blod', "Cr_umol":'Analyte Value'})
c16u['Analyte']='UCRT_umol'
##left innner join lc and demo 
m_c16u=pd.merge(
    c16u,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

llod=add_llod("UALB",0.30,"ug/mL", '2015-16')
llod=add_llod("UCRT",5.00,"mg/dL", '2015-16')


##13-14
lc14 = pd.read_sas('ALB_CR_H.XPT')
lc14=lc14.rename(columns={"SEQN": "Participant", 
                            "URXUMS": "Alb_mg", "URDUMALC": "Alb_Blod", 
                            "URXUCR" : "Cr_mg",
                            "URXCRS":"Cr_umol", "URDUCRLC": "Cr_Blod", 
                            "URDACT":"Alb_to_Cr", 'URXUMA':'Alb_ug'})
lc14=lc14[["Participant","Alb_mg","Cr_mg",
                            "Cr_umol",
                            "Alb_to_Cr", "Alb_ug"]]


##ASK TEAM< alb in mg or ug and cr in mg or umol
l14m=lc14[["Participant","Alb_mg"]]
l14m=l14m.rename(columns={ "Alb_mg":'Analyte Value'})
l14m['Analyte']='UALB_mg'
l14m['Blod']='99999'

##left innner join lc and demo 
m_l14m=pd.merge(
    l14m,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

#ASK TEAM< alb in mg or ug and cr in mg or umol
l14u=lc14[["Participant","Alb_ug"]]
l14u=l14u.rename(columns={ "Alb_ug":'Analyte Value'})
l14u['Analyte']='UALB_ug'
l14u['Blod']='99999'

##left innner join lc and demo 
m_l14u=pd.merge(
    l14u,
    d14,
how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c14m=lc14[["Participant","Cr_mg"]]
c14m=c14m.rename(columns={ "Cr_mg":'Analyte Value'})
c14m['Analyte']='UCRT_mg'
c14m['Blod']=9999

##left innner join lc and demo 
m_c14m=pd.merge(
    c14m,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c14u=lc14[["Participant","Cr_umol"]]
c14u=c14u.rename(columns={ "Cr_umol":'Analyte Value'})
c14u['Analyte']='UCRT_umol'
c14u['Blod']=9999
##left innner join lc and demo 
m_c14u=pd.merge(
    c14u,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

llod=add_llod("UALB",0.30,"ug/mL", '2013-14')
llod=add_llod("UCRT",5.00,"mg/dL", '2013-14')


##11-12
lc12 = pd.read_sas('ALB_CR_G.XPT')
lc12=lc12.rename(columns={"SEQN": "Participant", 
                            "URXUMS": "Alb_mg", "URDUMALC": "Alb_Blod", 
                            "URXUCR" : "Cr_mg",
                            "URXCRS":"Cr_umol", "URDUCRLC": "Cr_Blod", 
                            "URDACT":"Alb_to_Cr", 'URXUMA':'Alb_ug'})
lc12=lc12[["Participant","Alb_mg","Cr_mg",
                            "Cr_umol",
                            "Alb_to_Cr", "Alb_ug"]]


##ASK TEAM< alb in mg or ug and cr in mg or umol
l12m=lc12[["Participant","Alb_mg"]]
l12m=l12m.rename(columns={ "Alb_mg":'Analyte Value'})
l12m['Analyte']='UALB_mg'
l12m['Blod']=9999
##left innner join lc and demo 
m_l12m=pd.merge(
    l12m,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

#ASK TEAM< alb in mg or ug and cr in mg or umol
l12u=lc12[["Participant","Alb_ug"]]
l12u=l12u.rename(columns={"Alb_ug":'Analyte Value'})
l12u['Analyte']='UALB_ug'
l12u['Blod']=9999

##left innner join lc and demo 
m_l12u=pd.merge(
    l12u,
    d12,
how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)



##ASK TEAM< alb in mg or ug and cr in mg or umol
c12m=lc12[["Participant","Cr_mg"]]
c12m=c12m.rename(columns={ "Cr_mg":'Analyte Value'})
c12m['Analyte']='UCRT_mg'
c12m['Blod']=9999
##left innner join lc and demo 
m_c12m=pd.merge(
    c12m,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##ASK TEAM< alb in mg or ug and cr in mg or umol
c12u=lc12[["Participant","Cr_umol"]]
c12u=c12u.rename(columns={ "Cr_umol":'Analyte Value'})
c12u['Analyte']='UCRT_umol'
c12u['Blod']=9999

##left innner join lc and demo 
m_c12u=pd.merge(
    c12u,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)




##no llod provided

all_lc=pd.concat([m_l18m, m_l18u, m_l16m, m_l16u,m_l14m, m_l14u, m_l12m, m_l12u, m_c18m,
                  m_c18u, m_c16m,m_c16u, m_c14m, m_c14u, m_c12m, m_c12u])

In [5]:
##Chromium - Urine

##17-18
ucm18 = pd.read_sas('UCM_J.XPT')
ucm18=ucm18.rename(columns={"SEQN":"Participant",  "URXUCM": "Chrom",
                       "URDUCMLC" :"Chrom_Blod"})
ucm18=ucm18[['Participant',  'Chrom', 'Chrom_Blod']]
ucm18=ucm18.rename(columns={"Chrom":'Analyte Value','Chrom_Blod':'Blod'})
ucm18['Analyte']='UCR'


llod=add_llod("UCR",0.19,"ug/L", '2017-18')
##left innner join ucm and demo 
m_ucm18=pd.merge(
    ucm18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##15-16
##no urinary chromium data

##13-14
##no chromium data

##11-12
##no chromium data
all_ucm=m_ucm18

In [6]:
##Iodine - Urine

##17-18
uio18= pd.read_sas('UIO_J.XPT')
uio18=uio18.rename(columns={"SEQN":"Participant", "URXUIO": "I",
                       "URDUIOLC" :"I_Blod"})
uio18=uio18[['Participant', 'I', 'I_Blod']]
uio18=uio18.rename(columns={"I":'Analyte Value','I_Blod':'Blod'})
uio18['Analyte']='UI'
llod=add_llod("UI",2.4,"ug/L", '2017-18')
##left innner join uio and demo 
m_uio18=pd.merge(
    uio18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##15-16
uio16= pd.read_sas('UIO_I.XPT')
uio16=uio16.rename(columns={"SEQN":"Participant", "URXUIO": "I",
                       "URDUIOLC" :"I_Blod"})
uio16=uio16[['Participant', 'I', 'I_Blod']]
uio16=uio16.rename(columns={"I":'Analyte Value','I_Blod':'Blod'})
uio16['Analyte']='UI'
llod=add_llod("UI",2.4,"ug/L", '2015-16')
##left innner join uio and demo 
m_uio16=pd.merge(
    uio16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)


##13-14
uio14= pd.read_sas('UIO_H.XPT')
uio14=uio14.rename(columns={"SEQN":"Participant", "URXUIO": "I"})
uio14=uio14[['Participant', 'I']]
uio14=uio14.rename(columns={"I":'Analyte Value'})
uio14['Analyte']='UI'
uio14['Blod']=9999
llod=add_llod("UI",2.4,"ug/L", '2013-14')
##left innner join uio and demo 
m_uio14=pd.merge(
    uio14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)


##11-12
uio12= pd.read_sas('UIO_G.XPT')
uio12=uio12.rename(columns={"SEQN":"Participant", "URXUIO": "I"})
uio12=uio12[['Participant', 'I']]
uio12=uio12.rename(columns={"I":'Analyte Value'})
uio12['Analyte']='UI'
uio12['Blod']=9999
llod=add_llod("UI",2.4,"ug/L", '2011-12')
##left innner join uio and demo 
m_uio12=pd.merge(
    uio12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)


all_uio=pd.concat([m_uio18, m_uio16, m_uio14, m_uio12])

In [7]:
##Mercury - Urine

##17-18
uhg18= pd.read_sas('UHG_J.XPT')
uhg18=uhg18.rename(columns={"SEQN":"Participant", 'URXUHG': "Hg",
                       "URDUHGLC" :"Hg_Blod"})
uhg18=uhg18[['Participant', 'Hg', 'Hg_Blod']]
uhg18=uhg18.rename(columns={'Hg_Blod': "Blod","Hg":'Analyte Value'})
uhg18['Analyte']='UHG'
llod=add_llod("UHG",0.13,"ug/L", '2017-18')
##left innner join uhg and demo 
m_uhg18=pd.merge(
    uhg18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##15-16
uhg16= pd.read_sas('UHG_I.XPT')
uhg16=uhg16.rename(columns={"SEQN":"Participant", 'URXUHG': "Hg",
                       "URDUHGLC" :"Hg_Blod"})
uhg16=uhg16[['Participant', 'Hg', 'Hg_Blod']]
uhg16=uhg16.rename(columns={'Hg_Blod': "Blod","Hg":'Analyte Value'})
uhg16['Analyte']='UHG'
llod=add_llod("UHG",0.13,"ug/L", '2015-16')
##left innner join uhg and demo 
m_uhg16=pd.merge(
    uhg16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##13-14
uhg14= pd.read_sas('UHG_H.XPT')
uhg14=uhg14.rename(columns={"SEQN":"Participant", 'URXUHG': "Hg",
                       "URDUHGLC" :"Hg_Blod"})
uhg14=uhg14[['Participant', 'Hg', 'Hg_Blod']]
uhg14=uhg14.rename(columns={'Hg_Blod': "Blod","Hg":'Analyte Value'})
uhg14['Analyte']='UHG'
llod=add_llod("UHG",0.13,"ug/L", '2013-14')
##left innner join uhg and demo 
m_uhg14=pd.merge(
    uhg14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##11-12
##ASK , said inoraganic, same as others??
uhg12= pd.read_sas('UHG_G.XPT')
uhg12=uhg12.rename(columns={"SEQN":"Participant", 'URXUHG': "Hg",
                       "URDUHGLC" :"Hg_Blod"})
uhg12=uhg12[['Participant', 'Hg', 'Hg_Blod']]
uhg12=uhg12.rename(columns={'Hg_Blod': "Blod","Hg":'Analyte Value'})
uhg12['Analyte']='UHG'
##no llod
##left innner join uhg and demo 
m_uhg12=pd.merge(
    uhg12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

all_uhg=pd.concat([m_uhg18, m_uhg16, m_uhg14, m_uhg12])

In [8]:
##Metals - Urine

##17-18
um18= pd.read_sas('UM_J.XPT')
um18=um18.rename(columns={"SEQN":"Participant",  "URXUBA": "Ba",
                       "URDUBALC" :"Ba_Blod", "URXUCD":"Cd",
                     "URDUCDLC":"Cd_Blod", "URXUCO":"Co","URDUCOLC":"Co_Blod",
                     "URXUCS":"Cs","URDUCSLC":"Cs_Blod", 
                     "URXUMO":"Mo","URDUMOLC":"Mo_Blod","URXUMN":"Mn",
                      "URDUMNLC":"Mn_Blod","URXUPB":"Pb","URDUPBLC":"Pb_Blod",
                      "URXUSB":"Sb", "URDUSBLC":"Sb_Blod","URXUSN":"Sn",
                      "URDUSNLC":"Sn_Blod","URXUTL":"TI","URDUTLLC":"TI_Blod",
                      "URXUTU":"W", "URDUTULC":"W_Blod"})
um18=um18[['Participant',  'Ba', 'Ba_Blod', 'Cd', 'Cd_Blod', 'Co', 'Co_Blod',
      'Cs', 'Cs_Blod','Mo', 'Mo_Blod', 'Mn', 'Mn_Blod', 'Sb', 'Sb_Blod', 'Sn', 'Sn_Blod', 'TI', 'TI_Blod', 'W', 'W_Blod', 'Pb', 'Pb_Blod']]


llod=add_llod("UBA",0.060,"ug/L", '2017-18')
llod=add_llod("UCD",0.036,"ug/L", '2017-18')
llod=add_llod("UCS",0.086,"ug/L", '2017-18')
llod=add_llod("UCO",0.023,"ug/L", '2017-18')
llod=add_llod("UMN",0.13,"ug/L", '2017-18')
llod=add_llod("UMO",0.80,"ug/L", '2017-18')
llod=add_llod("UPB",0.03,"ug/L", '2017-18')
llod=add_llod("USB",0.022,"ug/L", '2017-18')
llod=add_llod("USN",0.018,"ug/L", '2017-18')
llod=add_llod("UTL",0.09,"ug/L", '2017-18')
llod=add_llod("UTU",0.018,"ug/L", '2017-18')

##barium
uba18=um18[['Participant', 'Ba', 'Ba_Blod']]
uba18=uba18.rename(columns={'Ba_Blod': "Blod","Ba":'Analyte Value'})
uba18['Analyte']='UBA'


##left innner join um and demo 
m_uba18=pd.merge(
    uba18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cd
ucd18=um18[['Participant', 'Cd', 'Cd_Blod']]
ucd18=ucd18.rename(columns={'Cd_Blod': "Blod","Cd":'Analyte Value'})
ucd18['Analyte']='UCD'
##left innner join um and demo 
m_ucd18=pd.merge(
    ucd18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##co
uco18=um18[['Participant', 'Co', 'Co_Blod']]
uco18=uco18.rename(columns={'Co_Blod': "Blod","Co":'Analyte Value'})
uco18['Analyte']='UCO'
##left innner join um and demo 
m_uco18=pd.merge(
    uco18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cs
ucs18=um18[['Participant', 'Cs', 'Cs_Blod']]
ucs18=ucs18.rename(columns={'Cs_Blod': "Blod","Cs":'Analyte Value'})
ucs18['Analyte']='UCS'
##left innner join um and demo 
m_ucs18=pd.merge(
    ucs18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mo
umo18=um18[['Participant', 'Mo', 'Mo_Blod']]
umo18=umo18.rename(columns={'Mo_Blod': "Blod","Mo":'Analyte Value'})
umo18['Analyte']='UMO'
##left innner join um and demo 
m_umo18=pd.merge(
    umo18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mn
umn18=um18[['Participant', 'Mn', 'Mn_Blod']]
umn18=umn18.rename(columns={'Mn_Blod': "Blod","Mn":'Analyte Value'})
umn18['Analyte']='UMN'
##left innner join um and demo 
m_umn18=pd.merge(
    umn18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##pb
upb18=um18[['Participant', 'Pb', 'Pb_Blod']]
upb18=upb18.rename(columns={'Pb_Blod': "Blod","Pb":'Analyte Value'})
upb18['Analyte']='UPB'
##left innner join um and demo 
m_upb18=pd.merge(
    upb18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

##sb
usb18=um18[['Participant', 'Sb', 'Sb_Blod']]
usb18=usb18.rename(columns={'Sb_Blod': "Blod","Sb":'Analyte Value'})
usb18['Analyte']='USB'
##left innner join um and demo 
m_usb18=pd.merge(
    usb18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##sn
usn18=um18[['Participant', 'Sn', 'Sn_Blod']]
usn18=usn18.rename(columns={'Sn_Blod': "Blod","Sn":'Analyte Value'})
usn18['Analyte']='USN'
##left innner join um and demo 
m_usn18=pd.merge(
    usn18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##Tl
uti18=um18[['Participant', 'TI', 'TI_Blod']]
uti18=uti18.rename(columns={'TI_Blod': "Blod","TI":'Analyte Value'})
uti18['Analyte']='UTL'
##left innner join um and demo 
m_uti18=pd.merge(
    uti18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##w
uw18=um18[['Participant', 'W', 'W_Blod']]
uw18=uti18.rename(columns={'W_Blod': "Blod","W":'Analyte Value'})
uw18['Analyte']='UTU'
##left innner join um and demo 
m_uw18=pd.merge(
    uw18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

metals18=pd.concat([m_uba18,m_ucd18,m_uco18,m_ucs18,m_umo18,m_umn18,
          m_upb18,m_usb18,m_usn18,m_uti18,m_uw18])

In [9]:
##Metals - Urine

##15-16
um16= pd.read_sas('UM_I.XPT')
um16=um16.rename(columns={"SEQN":"Participant",  "URXUBA": "Ba",
                       "URDUBALC" :"Ba_Blod", "URXUCD":"Cd",
                     "URDUCDLC":"Cd_Blod", "URXUCO":"Co","URDUCOLC":"Co_Blod",
                     "URXUCS":"Cs","URDUCSLC":"Cs_Blod", 
                     "URXUMO":"Mo","URDUMOLC":"Mo_Blod","URXUMN":"Mn",
                      "URDUMNLC":"Mn_Blod","URXUPB":"Pb","URDUPBLC":"Pb_Blod",
                      "URXUSB":"Sb", "URDUSBLC":"Sb_Blod","URXUSN":"Sn",
                      "URDUSNLC":"Sn_Blod","URXUTL":"TI","URDUTLLC":"TI_Blod",
                      "URXUTU":"W", "URDUTULC":"W_Blod"})
um16=um16[['Participant',  'Ba', 'Ba_Blod', 'Cd', 'Cd_Blod', 'Co', 'Co_Blod',
      'Cs', 'Cs_Blod','Mo', 'Mo_Blod', 'Mn', 'Mn_Blod', 'Sb', 'Sb_Blod', 'Sn', 'Sn_Blod', 'TI', 'TI_Blod', 'W', 'W_Blod', 'Pb', 'Pb_Blod']]
llod=add_llod("UBA",0.060,"ug/L", '2015-16')
llod=add_llod("UCD",0.036,"ug/L", '2015-16')
llod=add_llod("UCS",0.086,"ug/L", '2015-16')
llod=add_llod("UCO",0.023,"ug/L", '2015-16')
llod=add_llod("UMN",0.13,"ug/L", '2015-16')
llod=add_llod("UMO",0.80,"ug/L", '2015-16')
llod=add_llod("UPB",0.03,"ug/L", '2015-16')
llod=add_llod("USB",0.022,"ug/L", '2015-16')
llod=add_llod("USN",0.018,"ug/L", '2015-16')
llod=add_llod("UTL",0.09,"ug/L", '2015-16')
llod=add_llod("UTU",0.018,"ug/L", '2015-16')
#barium
uba16=um16[['Participant', 'Ba', 'Ba_Blod']]
uba16=uba16.rename(columns={'Ba_Blod': "Blod","Ba":'Analyte Value'})
uba16['Analyte']='UBA'


##left innner join um and demo 
m_uba16=pd.merge(
    uba16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cd
ucd16=um16[['Participant', 'Cd', 'Cd_Blod']]
ucd16=ucd16.rename(columns={'Cd_Blod': "Blod","Cd":'Analyte Value'})
ucd16['Analyte']='UCD'
##left innner join um and demo 
m_ucd16=pd.merge(
    ucd16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##co
uco16=um16[['Participant', 'Co', 'Co_Blod']]
uco16=uco16.rename(columns={'Co_Blod': "Blod","Co":'Analyte Value'})
uco16['Analyte']='UCO'
##left innner join um and demo 
m_uco16=pd.merge(
    uco16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cs
ucs16=um16[['Participant', 'Cs', 'Cs_Blod']]
ucs16=ucs16.rename(columns={'Cs_Blod': "Blod","Cs":'Analyte Value'})
ucs16['Analyte']='UCS'
##left innner join um and demo 
m_ucs16=pd.merge(
    ucs16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mo
umo16=um16[['Participant', 'Mo', 'Mo_Blod']]
umo16=umo16.rename(columns={'Mo_Blod': "Blod","Mo":'Analyte Value'})
umo16['Analyte']='UMO'
##left innner join um and demo 
m_umo16=pd.merge(
    umo16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mn
umn16=um16[['Participant', 'Mn', 'Mn_Blod']]
umn16=umn16.rename(columns={'Mn_Blod': "Blod","Mn":'Analyte Value'})
umn16['Analyte']='UMN'
##left innner join um and demo 
m_umn16=pd.merge(
    umn16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##pb
upb16=um16[['Participant', 'Pb', 'Pb_Blod']]
upb16=upb16.rename(columns={'Pb_Blod': "Blod","Pb":'Analyte Value'})
upb16['Analyte']='UPB'
##left innner join um and demo 
m_upb16=pd.merge(
    upb16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

##sb
usb16=um16[['Participant', 'Sb', 'Sb_Blod']]
usb16=usb16.rename(columns={'Sb_Blod': "Blod","Sb":'Analyte Value'})
usb16['Analyte']='USB'
##left innner join um and demo 
m_usb16=pd.merge(
    usb16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##sn
usn16=um16[['Participant', 'Sn', 'Sn_Blod']]
usn16=usn16.rename(columns={'Sn_Blod': "Blod","Sn":'Analyte Value'})
usn16['Analyte']='USN'
##left innner join um and demo 
m_usn16=pd.merge(
    usn16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##Ti
uti16=um16[['Participant', 'TI', 'TI_Blod']]
uti16=uti16.rename(columns={'TI_Blod': "Blod","TI":'Analyte Value'})
uti16['Analyte']='UTL'
##left innner join um and demo 
m_uti16=pd.merge(
    uti16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##w
uw16=um16[['Participant', 'W', 'W_Blod']]
uw16=uw16.rename(columns={'W_Blod': "Blod","W":'Analyte Value'})
uw16['Analyte']='UTU'
##left innner join um and demo 
m_uw16=pd.merge(
    uw16,
    d16,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

metals16=pd.concat([m_uba16,m_ucd16,m_uco16,m_ucs16,m_umo16,m_umn16,
          m_upb16,m_usb16,m_usn16,m_uti16,m_uw16])

In [10]:
##Metals - Urine

##13-14
um14= pd.read_sas('UM_H.XPT')
um14=um14.rename(columns={"SEQN":"Participant",  "URXUBA": "Ba",
                       "URDUBALC" :"Ba_Blod", "URXUCD":"Cd",
                     "URDUCDLC":"Cd_Blod", "URXUCO":"Co","URDUCOLC":"Co_Blod",
                     "URXUCS":"Cs","URDUCSLC":"Cs_Blod", 
                     "URXUMO":"Mo","URDUMOLC":"Mo_Blod","URXUMN":"Mn",
                      "URDUMNLC":"Mn_Blod","URXUPB":"Pb","URDUPBLC":"Pb_Blod",
                      "URXUSB":"Sb", "URDUSBLC":"Sb_Blod","URXUSN":"Sn",
                      "URDUSNLC":"Sn_Blod","URXUTL":"TI","URDUTLLC":"TI_Blod",
                      "URXUTU":"W", "URDUTULC":"W_Blod"})
um14=um14[['Participant',  'Ba', 'Ba_Blod', 'Cd', 'Cd_Blod', 'Co', 'Co_Blod',
      'Cs', 'Cs_Blod','Mo', 'Mo_Blod', 'Mn', 'Mn_Blod', 'Sb', 'Sb_Blod', 'Sn', 'Sn_Blod', 'TI', 'TI_Blod', 'W', 'W_Blod', 'Pb', 'Pb_Blod']]
llod=add_llod("UBA",0.060,"ug/L", '2013-14')
llod=add_llod("UCD",0.036,"ug/L", '2013-14')
##no llod for cesium
llod=add_llod("UCO",0.023,"ug/L", '2013-14')
llod=add_llod("UMN",0.13,"ug/L", '2013-14')
llod=add_llod("UMO",0.80,"ug/L", '2013-14')
llod=add_llod("UPB",0.03,"ug/L", '2013-14')
llod=add_llod("USB",0.022,"ug/L", '2013-14')
llod=add_llod("USN",0.018,"ug/L", '2013-14')
llod=add_llod("UTL",0.09,"ug/L", '2013-14')
llod=add_llod("UTU",0.018,"ug/L", '2013-14')

#barium
uba14=um14[['Participant', 'Ba', 'Ba_Blod']]
uba14=uba14.rename(columns={'Ba_Blod': "Blod","Ba":'Analyte Value'})
uba14['Analyte']='UBA'


##left innner join um and demo 
m_uba14=pd.merge(
    uba14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cd
ucd14=um14[['Participant', 'Cd', 'Cd_Blod']]
ucd14=ucd14.rename(columns={'Cd_Blod': "Blod","Cd":'Analyte Value'})
ucd14['Analyte']='UCD'
##left innner join um and demo 
m_ucd14=pd.merge(
    ucd14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##co
uco14=um14[['Participant', 'Co', 'Co_Blod']]
uco14=uco14.rename(columns={'Co_Blod': "Blod","Co":'Analyte Value'})
uco14['Analyte']='UCO'
##left innner join um and demo 
m_uco14=pd.merge(
    uco14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cs
ucs14=um14[['Participant', 'Cs', 'Cs_Blod']]
ucs14=ucs14.rename(columns={'Cs_Blod': "Blod","Cs":'Analyte Value'})
ucs14['Analyte']='UCS'
##left innner join um and demo 
m_ucs14=pd.merge(
    ucs14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mo
umo14=um14[['Participant', 'Mo', 'Mo_Blod']]
umo14=umo14.rename(columns={'Mo_Blod': "Blod","Mo":'Analyte Value'})
umo14['Analyte']='UMO'
##left innner join um and demo 
m_umo14=pd.merge(
    umo14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mn
umn14=um14[['Participant', 'Mn', 'Mn_Blod']]
umn14=umn14.rename(columns={'Mn_Blod': "Blod","Mn":'Analyte Value'})
umn14['Analyte']='UMN'
##left innner join um and demo 
m_umn14=pd.merge(
    umn14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##pb
upb14=um14[['Participant', 'Pb', 'Pb_Blod']]
upb14=upb14.rename(columns={'Pb_Blod': "Blod","Pb":'Analyte Value'})
upb14['Analyte']='UPB'
##left innner join um and demo 
m_upb14=pd.merge(
    upb14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

##sb
usb14=um14[['Participant', 'Sb', 'Sb_Blod']]
usb14=usb14.rename(columns={'Sb_Blod': "Blod","Sb":'Analyte Value'})
usb14['Analyte']='USB'
##left innner join um and demo 
m_usb14=pd.merge(
    usb14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##sn
usn14=um14[['Participant', 'Sn', 'Sn_Blod']]
usn14=usn14.rename(columns={'Sn_Blod': "Blod","Sn":'Analyte Value'})
usn14['Analyte']='USN'
##left innner join um and demo 
m_usn14=pd.merge(
    usn14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##Ti
uti14=um14[['Participant', 'TI', 'TI_Blod']]
uti14=uti14.rename(columns={'TI_Blod': "Blod","TI":'Analyte Value'})
uti14['Analyte']='UTL'
##left innner join um and demo 
m_uti14=pd.merge(
    uti14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##w
uw14=um14[['Participant', 'W', 'W_Blod']]
uw14=uw14.rename(columns={'W_Blod': "Blod","W":'Analyte Value'})
uw14['Analyte']='UTU'
##left innner join um and demo 
m_uw14=pd.merge(
    uw14,
    d14,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

metals14=pd.concat([m_uba14,m_ucd14,m_uco14,m_ucs14,m_umo14,m_umn14,
          m_upb14,m_usb14,m_usn14,m_uti14,m_uw14])

In [11]:
##Metals - Urine

##11-12
um12= pd.read_sas('UHM_G.XPT')
um12=um12.rename(columns={"SEQN":"Participant",  "URXUBA": "Ba",
                       "URDUBALC" :"Ba_Blod", "URXUCD":"Cd",
                     "URDUCDLC":"Cd_Blod", "URXUCO":"Co","URDUCOLC":"Co_Blod",
                     "URXUCS":"Cs","URDUCSLC":"Cs_Blod", 
                     "URXUMO":"Mo","URDUMOLC":"Mo_Blod","URXUMN":"Mn",
                      "URDUMNLC":"Mn_Blod","URXUPB":"Pb","URDUPBLC":"Pb_Blod",
                      "URXUSB":"Sb", "URDUSBLC":"Sb_Blod","URXUSN":"Sn",
                      "URDUSNLC":"Sn_Blod","URXUTL":"TI","URDUTLLC":"TI_Blod",
                      "URXUTU":"W", "URDUTULC":"W_Blod"})
um12=um12[['Participant',  'Ba', 'Ba_Blod', 'Cd', 'Cd_Blod', 'Co', 'Co_Blod',
      'Cs', 'Cs_Blod','Mo', 'Mo_Blod', 'Mn', 'Mn_Blod', 'Sb', 'Sb_Blod', 'Sn', 'Sn_Blod', 'TI', 'TI_Blod', 'W', 'W_Blod', 'Pb', 'Pb_Blod']]
llod=add_llod("UBA",0.1000,"ug/L", '2011-12')
llod=add_llod("UCD",0.0560,"ug/L", '2011-12')
llod=add_llod("UCO",0.0480,"ug/L", '2011-12')
llod=add_llod("UCS",0.1200,"ug/L", '2011-12')
llod=add_llod("UMN",0.0800,"ug/L", '2011-12')
llod=add_llod("UMO",0.9900,"ug/L", '2011-12')
llod=add_llod("UPB",0.0800,"ug/L", '2011-12')
llod=add_llod("USB",0.0410,"ug/L", '2011-12')
llod=add_llod("USN",0.0200,"ug/L", '2011-12')
llod=add_llod("UTL",0.2200,"ug/L", '2011-12')
llod=add_llod("UTU",0.0260,"ug/L", '2011-12')


#barium
uba12=um12[['Participant', 'Ba', 'Ba_Blod']]
uba12=uba12.rename(columns={'Ba_Blod': "Blod","Ba":'Analyte Value'})
uba12['Analyte']='UBA'


##left innner join um and demo 
m_uba12=pd.merge(
    uba12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cd
ucd12=um12[['Participant', 'Cd', 'Cd_Blod']]
ucd12=ucd12.rename(columns={'Cd_Blod': "Blod","Cd":'Analyte Value'})
ucd12['Analyte']='UCD'
##left innner join um and demo 
m_ucd12=pd.merge(
    ucd12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##co
uco12=um12[['Participant', 'Co', 'Co_Blod']]
uco12=uco12.rename(columns={'Co_Blod': "Blod","Co":'Analyte Value'})
uco12['Analyte']='UCO'
##left innner join um and demo 
m_uco12=pd.merge(
    uco12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##cs
ucs12=um12[['Participant', 'Cs', 'Cs_Blod']]
ucs12=ucs12.rename(columns={'Cs_Blod': "Blod","Cs":'Analyte Value'})
ucs12['Analyte']='UCS'
##left innner join um and demo 
m_ucs12=pd.merge(
    ucs12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mo
umo12=um12[['Participant', 'Mo', 'Mo_Blod']]
umo12=umo12.rename(columns={'Mo_Blod': "Blod","Mo":'Analyte Value'})
umo12['Analyte']='UMO'
##left innner join um and demo 
m_umo12=pd.merge(
    umo12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##mn
umn12=um12[['Participant', 'Mn', 'Mn_Blod']]
umn12=umo12.rename(columns={'Mn_Blod': "Blod","Mn":'Analyte Value'})
umn12['Analyte']='UMN'
##left innner join um and demo 
m_umn12=pd.merge(
    umn12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##pb
upb12=um12[['Participant', 'Pb', 'Pb_Blod']]
upb12=upb12.rename(columns={'Pb_Blod': "Blod","Pb":'Analyte Value'})
upb12['Analyte']='UPB'
##left innner join um and demo 
m_upb12=pd.merge(
    upb12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

##sb
usb12=um12[['Participant', 'Sb', 'Sb_Blod']]
usb12=usb12.rename(columns={'Sb_Blod': "Blod","Sb":'Analyte Value'})
usb12['Analyte']='USB'
##left innner join um and demo 
m_usb12=pd.merge(
    usb12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##sn
usn12=um12[['Participant', 'Sn', 'Sn_Blod']]
usn12=usn12.rename(columns={'Sn_Blod': "Blod","Sn":'Analyte Value'})
usn12['Analyte']='USN'
##left innner join um and demo 
m_usn12=pd.merge(
    usn12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##uti
uti12=um12[['Participant', 'TI', 'TI_Blod']]
uti12=uti12.rename(columns={'TI_Blod': "Blod","TI":'Analyte Value'})
uti12['Analyte']='UTL'
##left innner join um and demo 
m_uti12=pd.merge(
    uti12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)
##w
uw12=um12[['Participant', 'W', 'W_Blod']]
uw12=uw12.rename(columns={'W_Blod': "Blod","W":'Analyte Value'})
uw12['Analyte']='UTU'
##left innner join um and demo 
m_uw12=pd.merge(
    uw12,
    d12,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True)

metals12=pd.concat([m_uba12,m_ucd12,m_uco12,m_ucs12,m_umo12,m_umn12,
          m_upb12,m_usb12,m_usn12,m_uti12,m_uw12])

In [12]:
all_um=pd.concat([metals18, metals16, metals14, metals12])
all_um[all_um['Pregnant']==2.0].count()

Participant      15444
Analyte Value    15286
Blod             15286
Analyte          15444
Pregnant         15444
Age              15444
Marital          15444
Child_A          15444
Child_B          15444
H_Inc            15103
F_Inc            15125
Edu              15444
Rac              15444
Time_Period      15444
dtype: int64

In [13]:
##Nickel - Urine

##17-18
uni18= pd.read_sas('UNI_J.XPT')
uni18=uni18.rename(columns={"SEQN":"Participant", "URXUNI":"Ni","URDUNILC":"Ni_Blod"})
uni18=uni18[['Participant', 'Ni', 'Ni_Blod']]
uni18=uni18.rename(columns={'Ni_Blod': "Blod","Ni":'Analyte Value'})
uni18['Analyte']='UNI'
llod=add_llod("UNI",0.31,"ug/L", '2017-18')
##left innner join uni and demo 
m_uni18=pd.merge(
    uni18,
    d18,
    how="inner",
    on='Participant',
    left_index=False,
    right_index=False,
    copy=True,

)

##15-16
##no nickel

##13-14
##no nickel

##11-12
##no nickel

all_uni=m_uni18

In [14]:
##merging all analytes for final nhanes 
final_nhanes=pd.concat([all_lc, all_um, all_uni, all_uhg, all_uio, all_ucm])
final_nhanes=final_nhanes.rename(columns={'Analyte Value': 'Analyte_Value'})

In [15]:
##transforming NA's BLOD column to 9999
final_nhanes['Blod']=final_nhanes['Blod'].fillna(9999)
final_nhanes['Blod']=final_nhanes['Blod'].astype('int')
final_nhanes['Participant']=final_nhanes['Participant'].astype('int')

In [16]:
##number of pregnant participants in NHANES
print("Number of Pregnant Particpants in Nhanes: ","{}".format(final_nhanes[final_nhanes['Pregnant']==1.0].nunique()[0]))

Number of Pregnant Particpants in Nhanes:  247

In [17]:
## creating Data Dictionary for final_nhanes dataframe 
##mimssing: form_name, section_name

import numpy as np
labels=['Participant ID Number', 'Is the analyte value below the limit of detection?', 'Concentration value for the analyte',
   'The type of analyte', 'Is the participant pregnant?', 'Age in years of the participant', 
   'Martial status of the participant', 'Number of kids in the household 5 years old or less',
   'Number of kids in the household 6-17 years old','Annual Household Income','Annual Family Income',
   'Education Level for Adults 20 Years Old and Over','Race/Hispanic origin w/ NH (Non-Hispanic) Asian', 'Time when data was collected']
a_choices="UTAS, Urinary Total Arsenic | UALB_mg, Urinary Albumin in mg/L | UALB_ug, Urinary Albumin in ug/L | UCRT_mg, Urinary Creatinine in mg/dL | UCRT_umol, Urinary Creatinine in umol/L | UCR, Urinary Chromium in ug/L | I, Urinary Iodine in ug/L | UHG, Urinary Mercury in ug/L | UBA, Urinary Barium in ug/L | UCD, Urinary Cadmium in ug/L | UCO, Urinary Cobalt in ug/L | UCS, Urinary Cesium in ug/L | UMO,Urinary Molybdenum in ug/L | UMN, Urinary Manganese in ug/L | UPB, Urinary Lead in ug/L | USB, Urinary Antimony in ug/L | USN, Urinary Tin in ug/L | UTL, Urinary Thallium in ug/L | UTU, Urinary Tungsten in ug/L | UNI, Urinary Nickel in ug/L"
inc= '1, $\$$0 to $\$$4,999 | 2, $\$$5,000 to $\$$9,999 | 3, $\$$10,000 to $\$$14,999 | 4, $\$$15,000 to $\$$19,999 | 5, $\$$20,000 to $\$$24,999 | 6, $\$$25,000 to $\$$34,999 | 7, $\$$35,000 to $\$$44,999 | 8, $\$$45,000 to $\$$54,999 | 9, $\$$55,000 to $\$$64,999 | 10, $\$$$65,000 to $\$$74,999 | 12, $\$$20,000 and Over | 13, Under $\$$20,000 | 14, $\$$75,000 to $\$$99,999 | 15, $\$$100,000 and Over | 77, refused'
edu = '1, Less than 9th grade | 2, 9-11th grade (Includes 12th grade with no diploma) | 3, High school graduate/GED or equivalent | 4, Some college or AA degree | 5, College graduate or above | 7, Refused | 9, Do not know'
race = '1, Mexican American | 2, Other Hispanic | 3, Non-Hispanic White | 4, Non-Hispanic Black | 6, Non-Hispanic Asian | 7, Other Race - Including Multi-Racial'
tp = '2011-12, 2011 to 2012 | 2013-14, 2013 to 2014 | 2015-16, 2015 to 2016 | 2017-18, 2017 to 2018'
choices=["", '0, No | 1, Yes | 9999, NA', "", a_choices, "1, Pregnant | 2, Not pregnant | 3, Could not be determined",
         "", '1, Married | 2, Widowed | 3, Divorced | 4, Seperated | 5, Never married | 6, Living with partner | 7, Refused | 8, Do not know',
         "", "", inc, inc, edu, race, tp]
origin = ['Laboratory & Demographic data', 'Laboratory data', 'Laboratory data', 'Laboratory data',
         'Demographic data', 'Demographic data', 'Demographic data', 'Demographic data',
          'Demographic data', 'Demographic data', 'Demographic data', 'Demographic data', 'Demographic data', 'Laboratory & Demographic data']
d={'var_name':['Participant', 'Blod', 'Analyte_Value', 'Analyte', 'Pregnant', 'Age',
             'Marital', 'Child_A', 'Child_B', 'H_Inc', 'F_Inc', 'Edu', 'Rac','Time_Period'],
  'field_type': ["int64", "int64","float64",'str',"float64","float64","float64","int64",
                 "int64","float64","float64","float64","float64","str"],
   'section_name' : origin,  'field_label': labels, 'field_choices': choices ,
  'field_min': [62161.0, 0, 0.013, "", 1.0, 3.0, 1.0, 0, 0, 1.0, 1.0, 1.0,
                1.0,'2011-12'] , 'field_max' :[ 102956.0, 99999, 72155.3, "", 3.0,
                                                80.0, 99.0, 3, 4, 99.0, 99.0, 9.0, 7.0, '2017-18']}
dd=pd.DataFrame(data=d)
dd['cohort'] = 'NHANES'
dd['form_name'] = ""

In [18]:
##exporting df's to csv's
final_nhanes.to_csv('NHANES_BIO.csv')
llod.to_csv('NHANES_LLOD.csv')
dd.to_csv('NHANES_DD.csv')

In [19]:
# First is necessary to pivot the raw NEU dataset so it matches
# the requested features.

# This queries the RawNEU dataset and excludes some of the values
# TODO - Should we drop NaN here?
"""df = pd.DataFrame.from_records(
    RawNHANES_BIO.objects.
    # exclude(Creat_Corr_Result__lt=-1000).
    # exclude(Creat_Corr_Result__isnull=True).
    values()
)"""
df = final_nhanes.copy()




##only including pregnant participants
df_preg=df[df['Pregnant']==1.0]

## new covariates
df_preg['Member_c'] = 1
df_preg.columns = ['PIN_Patient', 'BLOD','Result', 'Analyte', 'Pregnant' , 'Age', 'Marital',
              'Child_A', 'Child_B','H_Inc', 'F_Inc', 'Edu', 'Rac', 'TimePeriod', 'Member_c']
df_preg

/tmp/ipykernel_1232/2212463505.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preg['Member_c'] = 1

,PIN_Patient,BLOD,Result,Analyte,Pregnant,Age,Marital,Child_A,Child_B,H_Inc,F_Inc,Edu,Rac,TimePeriod,Member_c
198,93929,0,6.50,UALB_mg,1.0,35.0,1.0,1,0,15.0,15.0,5.0,3.0,2017-18,1
255,94002,0,17.00,UALB_mg,1.0,27.0,1.0,1,1,14.0,14.0,5.0,4.0,2017-18,1
516,94302,0,5.00,UALB_mg,1.0,24.0,1.0,2,3,12.0,12.0,3.0,6.0,2017-18,1
604,94406,0,9.20,UALB_mg,1.0,34.0,1.0,0,3,99.0,99.0,4.0,4.0,2017-18,1
930,94783,0,12.10,UALB_mg,1.0,28.0,1.0,1,1,9.0,9.0,4.0,6.0,2017-18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075,100077,1,0.13,UCR,1.0,32.0,1.0,1,3,4.0,4.0,2.0,1.0,2017-18,1
2128,100258,0,0.23,UCR,1.0,25.0,1.0,0,0,8.0,8.0,2.0,3.0,2017-18,1
2180,100427,1,0.13,UCR,1.0,38.0,1.0,1,0,14.0,14.0,3.0,1.0,2017-18,1
2730,102184,1,0.13,UCR,1.0,25.0,1.0,1,0,9.0,9.0,4.0,6.0,2017-18,1
2872,102635,1,0.13,UCR,1.0,40.0,1.0,1,0,15.0,15.0,5.0,6.0,2017-18,1

In [29]:
import pandas as pd
import numpy as np
from datasets.models import RawNHANES_BIO, RawNHANES_LLOD
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels


def get_dataframe_orig():
   

    # First is necessary to pivot the raw NEU dataset so it matches
    # the requested features.

    # This queries the RawNEU dataset and excludes some of the values
    df = final_nhanes.copy()
    
    ##only including pregnant participants
    df_preg=df[df['Pregnant']==1.0]

    ##Only including participants ages 18-40
    df_preg=df_preg[df_preg['Age'] >=18]
    df_preg=df_preg[df_preg['Age'] <=40]

    ## new covariates
    df_preg['Member_c'] = 1
    df_preg.columns = ['PIN_Patient', 'BLOD','Result', 'Analyte', 'Pregnant' , 'Age', 'Marital',
                  'Child_A', 'Child_B','H_Inc', 'F_Inc', 'Edu', 'Rac', 'TimePeriod', 'Member_c']
    numerical_values = 'Result'

    columns_to_indexes = ['PIN_Patient', 'TimePeriod', 'Member_c' ]
    categorical_to_columns = ['Analyte']

    df_preg = pd.pivot_table(df_preg, values=numerical_values,
                        index=columns_to_indexes,
                        columns=categorical_to_columns)

    df_preg = df_preg.reset_index()
   
    

    # After pivot
    # Analyte     TimePeriod Member_c       BCD  ...      UTMO       UTU       UUR
    # PIN_Patient                                ...
    # A0000M               1        1  1.877245  ...  0.315638  1.095520  0.424221
    # A0000M               3        1  1.917757  ...  0.837639  4.549155  0.067877
    # A0001M               1        1  1.458583  ...  0.514317  1.262910  1.554346
    # A0001M               3        1  1.365789  ...  0.143302  1.692582  0.020716
    # A0002M               1        1  1.547669  ...  0.387643  0.988567  1.081877

    df_preg['CohortType'] = 'NHANES'
    
    return df_preg

In [30]:
test=get_dataframe_orig()
test

Analyte,PIN_Patient,TimePeriod,Member_c,UALB_mg,UALB_ug,UBA,UCD,UCO,UCR,UCRT_mg,...,UI,UMN,UMO,UNI,UPB,USB,USN,UTL,UTU,CohortType
0,62415,2011-12,1,9.7,9.7,NaN,NaN,NaN,NaN,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
1,63061,2011-12,1,19.2,19.2,NaN,NaN,NaN,NaN,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
2,63080,2011-12,1,8.5,8.5,2.93,0.267,0.486,NaN,144.0,...,185.9,76.400,76.40,NaN,0.69,0.029,5.97,0.244,0.126,NHANES
3,63197,2011-12,1,37.2,37.2,NaN,NaN,NaN,NaN,129.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
4,63858,2011-12,1,11.1,11.1,NaN,NaN,NaN,NaN,176.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,101765,2017-18,1,5.2,5.2,NaN,NaN,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
227,101973,2017-18,1,3.4,3.4,NaN,NaN,NaN,NaN,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES
228,102184,2017-18,1,19.3,19.3,3.06,0.104,2.166,0.13,106.0,...,72.2,0.092,36.62,2.25,0.29,0.042,0.70,0.355,0.355,NHANES
229,102635,2017-18,1,9.5,9.5,2.89,0.543,0.643,0.13,153.0,...,255.7,0.330,62.18,1.08,0.31,0.085,0.24,0.383,0.383,NHANES
230,102682,2017-18,1,6.8,6.8,NaN,NaN,NaN,NaN,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHANES